version: '3.8'

services:
  postgres:
    container_name: course-management-postgres
    image: postgres:latest
    restart: always
    
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "1234:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data 

  course-management:
    build: .
    container_name: course-management
    env_file:
      - .env
    ports: 
      - "5000:5000"
    depends_on:
      - postgres
volumes:
  postgres_data: