services:
  postgres:
    container_name: course-management-postgres
    image: postgres:latest
    restart: always
    
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "1234:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data 
    networks:
      - course-management-network

  course-management-api:
    build: .
    image: course-management-api
    container_name: course-management-api
    env_file:
      - .env
    ports: 
      - "5000:5000"
    depends_on:
      - postgres
    networks:
      - course-management-network

networks:
  course-management-network:
    driver: bridge
    
volumes:
  postgres_data: